name:                ron-benchmark
version:             0.1.0
license:             BSD3
author:              "d86leader"
maintainer:          "d86leader@mail.com"
synopsis:            Benchmarks RON

executables:
  bench-exe:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -Wcompat -Wno-missing-signatures
    dependencies:
    - base
    - ron-hs
    - bytestring
    - containers
    - text
    - time
